version: '3.8'
services:
  postgres:
    container_name: ad_postgres
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

  sequra-assignment:
    # Nokogori dependency issue with m1 - https://stackoverflow.com/a/71787531
    platform: linux/x86_64
    build: .
    image: sequra-assignment
    container_name: sequra-assignment
    environment:
      RAILS_ROOT:         /sequra-assignment
      REDIS_URL:          redis://redis:6379
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis

  redis:
    container_name: sequra_redis
    image: redis:alpine
    command: redis-server --appendonly yes
    logging:
      driver: 'json-file'
      options:
        max-size: 1m
    ports:
      - 6379:6379

volumes:
  postgres:
    driver: local